const s = {
  entity: "event",
  account_id: "acc_QOsXJiDBQNha83",
  event: "subscription.charged",
  contains: ["subscription", "payment"],
  payload: {
    subscription: {
      entity: {
        id: "sub_QTckjrhwoHKpK8",
        entity: "subscription",
        plan_id: "plan_QTc7P2tnruOuMX",
        customer_id: "cust_QSX2cOk4DyeJj9",
        status: "active",
        current_start: 1746967378,
        current_end: 1749580200,
        ended_at: null,
        quantity: 1,
        notes: [],
        charge_at: 1749580200,
        start_at: 1746967378,
        end_at: 1783708200,
        auth_attempts: 0,
        total_count: 15,
        paid_count: 1,
        customer_notify: true,
        created_at: 1746966989,
        expire_by: null,
        short_url: null,
        has_scheduled_changes: false,
        change_scheduled_at: null,
        source: "dashboard",
        payment_method: "upi",
        offer_id: null,
        remaining_count: 14,
      },
    },
    payment: {
      entity: {
        id: "pay_QTcrZZp0tMKHVC",
        entity: "payment",
        amount: 10000,
        currency: "INR",
        status: "captured",
        order_id: "order_QTckkclvzTEaor",
        invoice_id: "inv_QTckkTUPq7ni7i",
        international: false,
        method: "upi",
        amount_refunded: 0,
        amount_transferred: 0,
        refund_status: null,
        captured: "1",
        description: "Yearly Subscription (2 months free!)",
        card_id: null,
        bank: null,
        wallet: null,
        vpa: "testuser@razorpay",
        email: "guptas3067@gmail.com",
        contact: "+919920597987",
        customer_id: "cust_QSX2cOk4DyeJj9",
        token_id: "token_QTcraK79UvPqTh",
        notes: [],
        fee: 236,
        tax: 36,
        error_code: null,
        error_description: null,
        acquirer_data: {
          rrn: "001000100002",
          upi_transaction_id: "npci_txn_id_for_QTcrZZp0tMKHVC",
        },
        created_at: 1746967378,
      },
    },
  },
  created_at: 1746967447,
};

const b = {
  entity: "event",
  account_id: "acc_QOsXJiDBQNha83",
  event: "subscription.activated",
  contains: ["subscription", "payment"],
  payload: {
    subscription: {
      entity: {
        id: "sub_QTckjrhwoHKpK8",
        entity: "subscription",
        plan_id: "plan_QTc7P2tnruOuMX",
        customer_id: "cust_QSX2cOk4DyeJj9",
        status: "active",
        current_start: 1746967378,
        current_end: 1749580200,
        ended_at: null,
        quantity: 1,
        notes: [],
        charge_at: 1749580200,
        start_at: 1746967378,
        end_at: 1783708200,
        auth_attempts: 0,
        total_count: 15,
        paid_count: 1,
        customer_notify: true,
        created_at: 1746966989,
        expire_by: null,
        short_url: null,
        has_scheduled_changes: false,
        change_scheduled_at: null,
        source: "dashboard",
        payment_method: "upi",
        offer_id: null,
        remaining_count: 14,
      },
    },
    payment: {
      entity: {
        id: "pay_QTcrZZp0tMKHVC",
        entity: "payment",
        amount: 10000,
        currency: "INR",
        status: "captured",
        order_id: "order_QTckkclvzTEaor",
        invoice_id: "inv_QTckkTUPq7ni7i",
        international: false,
        method: "upi",
        amount_refunded: 0,
        amount_transferred: 0,
        refund_status: null,
        captured: "1",
        description: "Yearly Subscription (2 months free!)",
        card_id: null,
        bank: null,
        wallet: null,
        vpa: "testuser@razorpay",
        email: "guptas3067@gmail.com",
        contact: "+919920597987",
        customer_id: "cust_QSX2cOk4DyeJj9",
        token_id: "token_QTcraK79UvPqTh",
        notes: [],
        fee: 236,
        tax: 36,
        error_code: null,
        error_description: null,
        acquirer_data: {
          rrn: "001000100002",
          upi_transaction_id: "npci_txn_id_for_QTcrZZp0tMKHVC",
        },
        created_at: 1746967378,
      },
    },
  },
  created_at: 1746967446,
};





const c = {
  entity: "event",
  account_id: "acc_QOsXJiDBQNha83",
  event: "subscription.authenticated",
  contains: ["subscription"],
  payload: {
    subscription: {
      entity: {
        id: "sub_QTckjrhwoHKpK8",
        entity: "subscription",
        plan_id: "plan_QTc7P2tnruOuMX",
        customer_id: "cust_QSX2cOk4DyeJj9",
        status: "active",
        current_start: 1746967378,
        current_end: 1749580200,
        ended_at: null,
        quantity: 1,
        notes: [],
        charge_at: 1749580200,
        start_at: 1746967378,
        end_at: 1783708200,
        auth_attempts: 0,
        total_count: 15,
        paid_count: 1,
        customer_notify: true,
        created_at: 1746966989,
        expire_by: null,
        short_url: null,
        has_scheduled_changes: false,
        change_scheduled_at: null,
        source: "dashboard",
        payment_method: "upi",
        offer_id: null,
        remaining_count: 14,
      },
    },
  },
  created_at: 1746967446,
};
